### ISSUE TITLE
Kudos & Feedback

### ISSUE THREAD

**Issue by AKeeganDev** [RaoAkif/ConferencePage#6]
**Kudos:**

- Nice job with including the google translation! Given the theme of your page it makes perfect sense to have this for a good user experience. I like that a lot!

- Also, nice job with blending the background into the navigation bars. Normally in designs you see a solid color across the page. Your style and uniqueness is coming through in your design and it is nice to see!

- The font and styles make everything easy to read!

- Nice job using objects for your main events. 

**Considerations:**

- It appears the mobile menu triggered by your hamburger throws an error on the about page. 

- The element on the page that appears as a button could be wrapped in a button tag for semantic purposes

- In the "main events" section you could use flex-wrap & flex-direction to wrap the cards. It appears that when using smaller screen sizes the cards come off the page at 768px to 1,000px (approximately).

- Could have used one file to save the data, and another for the js functionality.

- Its good practice to use lowercase camelcase for variable names. For example in line 102, 116. The convention is to use uppercase camelcase for classnames or global constants.

- On your readme file, kindly try to put your usernames show on the links, easier to read.

- Your main page title could be more descriptive for SEO reasons

- Kindly try to be more semantic with HTML and use sections, header, elements in order to have a better html backbone flow.

**Comment by RaoAkif** [comment]
I have incorporated all the recommended changes. Thanks for mentioning the issues.
